export const ASSOCIATE_TAGS_WITH_YOUR_FIELDS=6.2;
export const PROVIDE_INSTRUCTIONS_FOR_DATA_ENTRY=6.5;

export const DESCRIBE_LINKS_CLEARLY_AND_SUCCINCTLY=3.5;

export const PROVIDE_TEXT_ALTERNATIVE_TO_WEBSITE_IMAGES=3.6;

export const IN_TABLES_USES_TITLE_AND_SUMMARIES_APPROPRIATELY=3.9; 

export const PROVIDE_ALTERNATIVE_TO_AUDIO=5.2;

export const PROVIDE_TEXT_ALTERNATIVE_TO_FORM_IMAGE_BUTTONS=6.1;