export const ASSOCIATE_TAGS_WITH_YOUR_FIELDS=6.2;
export const PROVIDE_INSTRUCTIONS_FOR_DATA_ENTRY=6.5;
export const DESCRIBE_LINKS_CLEARLY_AND_SUCCINCTLY=3.5;

export const PROVIDE_TEXT_ALTERNATIVE_TO_FORM_IMAGE_BUTTONS=6.1;